### ISSUE TITLE
Recommended addition to the readme. Explain why you would want to fallback to heap for large data

### ISSUE THREAD

**Issue by benjaminmcdonald** [andylokandy/smallbox#12]

**Comment by andylokandy** [comment]
I think it's pretty straight forward. If smallbox wants to be compatible with the original box, we can't let some input (some types), which is originally valid, fail in smallbox.

BTW, back into the v0.1 or v0.2 of this crate, heap-fallback is an optional feature, because this crate was made for embedded devices in the first place. But then, I realized that embedded devices don't need DST! Well, so instead of deprecating the crate, I made it into an optimization tool for the modern platform.

However, thanks for your advice!
